import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import HeroSection from '@/components/HeroSection'
import TrustBar from '@/components/TrustBar'
import BenefitsGrid from '@/components/BenefitsGrid'
import ProcessTimeline from '@/components/ProcessTimeline'
import TestimonialsGrid from '@/components/TestimonialsGrid'
import type { PageParams } from '@/types/page.types'
import type { EnhancedPageData, ContentData } from '@/types/content-data'

// Import pages from Airtable export (content.json)
// Generated by: npm run export-airtable
import contentDataJson from '@/../../content.json'

const contentData = contentDataJson as ContentData
const PAGES: EnhancedPageData[] = contentData.pages

// CRITICAL: Next.js 15 requires this for static export
export async function generateStaticParams() {
  return PAGES.map((page) => ({
    service: page.service,
    location: page.location,
  }))
}

// Dynamic metadata generation
export async function generateMetadata({
  params,
}: {
  params: Promise<PageParams>
}): Promise<Metadata> {
  // Next.js 15 breaking change: params is now async
  const { service, location } = await params

  const pageData = PAGES.find(
    (p) => p.service === service && p.location === location
  )

  if (!pageData) {
    return {
      title: 'Page Not Found',
    }
  }

  return {
    title: pageData.seo.title,
    description: pageData.seo.description,
  }
}

// Page component
export default async function ServiceLocationPage({
  params,
}: {
  params: Promise<PageParams>
}) {
  // Next.js 15 breaking change: params is now async
  const { service, location } = await params

  const pageData = PAGES.find(
    (p) => p.service === service && p.location === location
  )

  if (!pageData) {
    notFound()
  }

  return (
    <main>
      <HeroSection hero={pageData.hero} branding={pageData.branding} />
      <TrustBar trustBar={pageData.trustBar} branding={pageData.branding} />
      <BenefitsGrid benefits={pageData.content.benefits} />
      <ProcessTimeline steps={pageData.content.processSteps} />
      <TestimonialsGrid testimonials={pageData.socialProof.testimonials} />
      <section className="max-w-4xl mx-auto py-8 px-4">
        <h2 className="text-3xl font-bold mb-6">About This Page</h2>
        <p className="text-lg mb-4">
          This is a dynamically generated page using Next.js 15&apos;s{' '}
          <code className="bg-gray-100 px-2 py-1 rounded">generateStaticParams()</code> function.
        </p>
        <div className="bg-gray-50 p-6 rounded-lg">
          <h3 className="font-semibold mb-2">Page Data:</h3>
          <ul className="space-y-1 text-sm font-mono">
            <li>Service: {service}</li>
            <li>Location: {location}</li>
          </ul>
        </div>
      </section>
    </main>
  )
}
