name: Export Airtable to content.json

on:
  # Manual trigger via GitHub UI
  workflow_dispatch:

  # Airtable webhook trigger (for future automation)
  repository_dispatch:
    types: [airtable-approved]

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Export Airtable data
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: npm run export-airtable

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code content.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add content.json
          git commit -m "Update content.json from Airtable export

          Automated export triggered by ${{ github.event_name }}

          🤖 Generated by GitHub Actions"
          git push origin master

      - name: No changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: echo "No changes detected in content.json - skipping commit"
